Update pyproject.toml
Problem: failure to extract ecoinvent to memory (biosphere extraction to file was fine)

Solution/workaround: install only py7zr<=1.0.0rc1

Cause:
ecoinvent_importer.py has an import function 'read_archive_to_bytes' for the .7z file that reads to memory using 'archive.read(file_list)'

This attribute doesn't exist in py7zr >1.0rc1 (which was the version installed by default) 

The most recent py7zr version has some other way to do this. See the changelog snippet below:

"""
Incompatible change
===================

There is incompatible change between v1.0.0-rc1 to v1.0.0-rc2.
I abandon methods ``read`` and ``readall``.
When you want to extract the archive to memory, you need to use
``extract`` method with ``factory`` argument. The ``factory`` takes a factory class, as of the GoF design pattern,
that provides object implements ``Py7zIO`` interface as a call back instance.
``SevenZipFile`` extract and write uncompressed data into your ``Py7zIO`` object.
"""
 
Error message with py7zr==1.0.0rc3:

"""
Wrote 633 LCIA methods with 481813 characterization factors
13:31:54 | INFO | Extracting .7z archive to memory
Error calling Python override of QThread::run(): 13:31:54 | ERROR | AttributeError: 'SevenZipFile' object has no attribute 'read'
Traceback (most recent call last):
  File "/media/stew/s2-ssd-data/code/gh/activity-browser/activity_browser/ui/threading.py", line 43, in run
    raise e
  File "/media/stew/s2-ssd-data/code/gh/activity-browser/activity_browser/ui/threading.py", line 39, in run
    self.run_safely(*self._args, **self._kwargs)
  File "/media/stew/s2-ssd-data/code/gh/activity-browser/activity_browser/actions/database/database_import_from_ecoinvent.py", line 420, in run_safely
    importer.install_ecoinvent(database_name, biosphere_name)
  File "/media/stew/s2-ssd-data/code/gh/activity-browser/activity_browser/bwutils/io/ecoinvent_importer.py", line 75, in install_ecoinvent
    spold_bytes = self.read_archive_to_bytes()
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/media/stew/s2-ssd-data/code/gh/activity-browser/activity_browser/bwutils/io/ecoinvent_importer.py", line 126, in read_archive_to_bytes
    extracted_data = archive.read(file_list)
                     ^^^^^^^^^^^^
AttributeError: 'SevenZipFile' object has no attribute 'read'
13:35:14 | INFO | Extracting .7z archive to memory
Error calling Python override of QThread::run(): 13:35:14 | ERROR | AttributeError: 'SevenZipFile' object has no attribute 'read'
Traceback (most recent call last):
  File "/media/stew/s2-ssd-data/code/gh/activity-browser/activity_browser/ui/threading.py", line 43, in run
    raise e
  File "/media/stew/s2-ssd-data/code/gh/activity-browser/activity_browser/ui/threading.py", line 39, in run
    self.run_safely(*self._args, **self._kwargs)
  File "/media/stew/s2-ssd-data/code/gh/activity-browser/activity_browser/actions/database/database_import_from_ecoinvent.py", line 420, in run_safely
    importer.install_ecoinvent(database_name, biosphere_name)
  File "/media/stew/s2-ssd-data/code/gh/activity-browser/activity_browser/bwutils/io/ecoinvent_importer.py", line 75, in install_ecoinvent
    spold_bytes = self.read_archive_to_bytes()
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/media/stew/s2-ssd-data/code/gh/activity-browser/activity_browser/bwutils/io/ecoinvent_importer.py", line 126, in read_archive_to_bytes
    all_files = archive.readall()
                     ^^^^^^^^^^^^
AttributeError: 'SevenZipFile' object has no attribute 'read'
"""